language: none

jobs:
  - name: container_single_task
    type: runSh
    on_failure:
      - script: echo ${MSG}
    steps:
      - TASK:
          name: task
          script:
            - script: export MSG=THIS_IS_A_TEST
            - unameeeeeeeeeee -a
